version: '3'
services:
  nextjs:
    build: ./front
    ports:
      - 3000:3000
    networks:
      proyect_net:
        ipv4_address: 172.20.0.2
  langchain:
    build: ./server
    ports:
      - 8000:8000
    env_file: ./server/.env
    networks:
      proyect_net:
        ipv4_address: 172.20.0.3
networks:
  proyect_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
